[theme]
primaryColor = "#1abc9c"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#2c2c2c"
textColor = "#f5f5f5"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[ui]
hideTopBar = false
